### ISSUE TITLE
Import and install error on astroquery

### ISSUE THREAD

**Issue by laserkelvin** [jnicoleoliveira/SPECData#10]
Ran into an issue with installing astroquery on Debian: the `cryptography` module failed to build because of a missing openssl files during compilation.

Running `sudo apt-get openssl` did not solve the problem, as it was already installed on the machine.

The workaround is to install cryptography through conda:

`conda install cryptography`

and then try installing astroquery again via PyPi `pip install astroquery`.

**Comment by jnicoleoliveira** [comment]
This is great, thanks Kelvin!
