### ISSUE TITLE
MacOSX install shell script

### ISSUE THREAD

**Issue by laserkelvin** [jnicoleoliveira/SPECData#16]
Ran into some non-fatal errors running the install script on an existing conda installation.

Upon running the script, I get this message before the wizard opens:
```
SpecNotFound: Invalid name, try the format: user/package
specdata-env does not exist or can't be accessed
Conda Env Exception: bin/conda_environment_osx.yml file not found
There is no requirements.txt
Open Environment..
CondaEnvironmentNotFoundError: Could not find environment: specdata-env .
You can list all discoverable environments with conda info --envs.
```

The install wizard proceeds up to the point of selecting the location for the executable to be produced, and hitting the browse button comes up with this error:

```Traceback (most recent call last):
  File "/Users/kelvin/Google Drive/Git/specdata/SPECData/app/dialogs/setup_wizard/dialog___create_executable.py", line 52, in <lambda>
    self.select_btn.clicked.connect((lambda x: save_as_file(self.file_txt, self.executable_ext)))
  File "/Users/kelvin/Google Drive/Git/specdata/SPECData/app/events.py", line 54, in save_as_file
    file_path = QFileDialog.getSaveFileName(w, 'Save As', os.path.curdir, filters, selected_filter)
TypeError: getSaveFileName(parent: QWidget = None, caption: QString = QString(), directory: QString = QString(), filter: QString = QString(), selectedFilter: QString = None, options: QFileDialog.Options = 0): argument 4 has unexpected type 'NoneType'```

**Comment by jnicoleoliveira** [comment]
Hi Kelvin,

It looks like OSX needs to omit the "env" tag when creating an environment.
From -> `conda env create -n specdata-env -f bin/conda_environment_osx.yml`
To     -> `conda create -n specdata-env -f bin/conda_environment_osx.yml`

**Comment by jnicoleoliveira** [comment]
I just pushed the change. 
Could you let me know if that solves it? Thanks.

**Comment by jnicoleoliveira** [comment]
Actually, the name of the .yml file was mispelled. Just  pushed the change on the master.

**Comment by jnicoleoliveira** [comment]
I fixed the error handling, and the OS check for OSX. Should take care of that second error.

>   File "/Users/kelvin/Google Drive/Git/specdata/SPECData/app/dialogs/setup_wizard/dialog___create_executable.py", line 52, in <lambda>
    self.select_btn.clicked.connect((lambda x: save_as_file(self.file_txt, self.executable_ext)))
  File "/Users/kelvin/Google Drive/Git/specdata/SPECData/app/events.py", line 54, in save_as_file
    file_path = QFileDialog.getSaveFileName(w, 'Save As', os.path.curdir, filters, selected_filter)
TypeError: getSaveFileName(parent: QWidget = None, caption: QString = QString(), directory: QString = QString(), filter: QString = QString(), selectedFilter: QString = None, options: QFileDialog.Options = 0): argument 4 has unexpected type 'NoneType'```
