### ISSUE TITLE
Windows Install Failure

### ISSUE THREAD

**Issue by jnicoleoliveira** [jnicoleoliveira/SPECData#18]
The installer for Windows gets caught up when installing an Anaconda enviornment..
The following occurs:

`C:\Users\Jasmine\Desktop\SPECdata\Versions\3.2\SPECData\SPECData-master\init>conda env create -n specdata-env -f bin/conda_environment_linux.yml`

> Fetching package metadata ...........
> NoPackagesFoundError: Package missing in current win-64 channels:
>   - cairo 1.14.8 0

**Comment by jnicoleoliveira** [comment]
The windows installer is currently using a Linux environment as a temporary substitute... going to create and add a Windows specific environment, and update the procedure.

**Comment by laserkelvin** [comment]
You'll need to make a conda environment from scratch on Windows - if you're using the Linux yaml file it'll look in the Linux channels for packages. 

The yaml files are not cross-platform, so we'll need one for each OS.

**Comment by jnicoleoliveira** [comment]
@laserkelvin 
I figured so. I think I put that as a temporary solution til I could get my hands on a Windows machine for testing. I'm creating/testing a new environment now. 
Thanks :)
