### ISSUE TITLE
SPECData gets stuck creating new experiment

### ISSUE THREAD

**Issue by laserkelvin** [jnicoleoliveira/SPECData#26]
GUI locks at "Creating data points" at 40%.

Running this in a terminal revealed that there was an import failure and no exception raised.

For some reason, it was trying to import `scipy` but it wasn't installed in the conda environment! Running `pip install scipy` fixed this, but we should add these packages to the YAML file.

**Comment by jnicoleoliveira** [comment]
Looks like the scipy package is missing from the anaconda environment. I'll have to

1. Ensure the package is in all environment .yml files.
2. Update the package list for checking requirements in the wizard.

I will have to update this.

Thanks Kelvin!
