### ISSUE TITLE
ImportError: No module named 'PyQt4'

### ISSUE THREAD

**Issue by laserkelvin** [jnicoleoliveira/SPECData#9]
Attempting to run SPECData on a stock conda installation with Python 3 gave me this error on a Mac OSX installation and on Linux.

The workaround is to make a new conda environment, specifying these options:

`conda create -n SPECData python=2.7 qt=4 matplotlib`

...and installing the remaining packages with PyPi.

This is related to: https://github.com/ContinuumIO/anaconda-issues/issues/1158

**Comment by jnicoleoliveira** [comment]
Thanks Kelvin!

**Comment by jnicoleoliveira** [comment]
#6 is another solution for OSX.
